# site settings
title: Colin Barrett's Personal Website
subtitle:
email: youremailaddress@gmail.com
description: Welcome to my site.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://cbarre01.github.io// # the base hostname & protocol for your site
author: Colin Barrett
street_address: 75 Loma Road
city: San Carlos
state: CA	
zip_code: 94070
country: United States of America
phone: (650) 339-1624

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url:
github_url: https://github.com/cbarre01
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/colin-barrett-stats/
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
